# -*- coding: utf-8 -*-
"""D2 R1 AI Neuroscience.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K-a7fFKmKWw_KQyCZ_5PJb-2duV7ZiUX

PART I: INFRASTRUCTURE & MULTI-SUBJECT INGESTION
"""

# Commented out IPython magic to ensure Python compatibility.
# =============================================================================
# CELL 1: ENVIRONMENT PROVISIONING & GLOBAL CONFIGS
# =============================================================================
print("Starting Cell 1: Initializing infrastructure and dependencies...")

# 1. Install heavy dependencies quietly
print("Installing pip packages (nilearn, nibabel, datalad, torch)...")
# %pip install -q nilearn nibabel pandas datalad tqdm matplotlib seaborn
# %pip install -q torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

# 2. Install system-level git-annex and network configurations
print("Installing git-annex standalone package...")
!wget -nc -q https://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-amd64.tar.gz -O /tmp/git-annex-standalone-amd64.tar.gz
!mkdir -p /usr/local/lib/git-annex
!tar -xzf /tmp/git-annex-standalone-amd64.tar.gz -C /usr/local/lib/git-annex --strip-components=1

# Inject into environment path
import os
os.environ['PATH'] = '/usr/local/lib/git-annex:' + os.environ['PATH']
!ln -sf /usr/local/lib/git-annex/git-annex /usr/local/bin/git-annex
!ln -sf /usr/local/lib/git-annex/git-annex-shell /usr/local/bin/git-annex-shell

print("Reinstalling netbase for robust network protocols...")
!apt-get update -qq && apt-get install -y --reinstall netbase > /dev/null 2>&1

# 3. Configure Git Globally (Required for DataLad tracking)
print("Configuring global Git settings...")
!git config --global user.email "neuro_decoder@colab.internal"
!git config --global user.name "NeuroDecoderColab"
!git config --global init.defaultBranch main
!git config --global annex.backend-prefer "SHA256"
!git config --global annex.retry "3"

# 4. Core Python Imports
print("Importing core analytics frameworks...")
import pandas as pd
import numpy as np
import json
import sys
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import torch

# Neuroimaging tools
from nilearn import datasets, plotting
from nilearn.image import load_img, smooth_img, index_img
from nilearn.masking import compute_epi_mask, apply_mask

# Scikit-learn wrapper utilities
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.model_selection import StratifiedKFold, permutation_test_score
from sklearn.preprocessing import StandardScaler

# Set plotting defaults
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette("husl")
# %matplotlib inline

print("\nCELL 1 FINISHED: Environment is provisioned.")

# =============================================================================
# CELL 1-CHECK: HARDWARE & DEPENDENCIES SANITY AUDIT
# =============================================================================
print("Running Cell 1 Validation Check...\n")

# Check PyTorch & CUDA Capabilities
print(f"PyTorch Installation Version: {torch.__version__}")
cuda_available = torch.cuda.is_available()
print(f"CUDA GPU Acceleration Available: {cuda_available}")

if cuda_available:
    device_name = torch.cuda.get_device_name(0)
    device = torch.device('cuda')
    print(f"Hardware Target Found: Using GPU [{device_name}]")

    # Run a quick 1-second sanity computation directly inside the GPU cores
    print("Running GPU tensor-matrix verification test...")
    x = torch.rand(1000, 1000, device=device)
    y = torch.matmul(x, x)
    del x, y
    torch.cuda.empty_cache()
    print("GPU Verification Test: Matrix multiplication completed instantly.")
else:
    device = torch.device('cpu')
    print("WARNING: No GPU detected. Processing will fall back to CPU.")
    print("    If you are using Google Colab, go to Runtime -> Change runtime type -> Select T4 GPU.")

# Check Nilearn Atlas access
print("\nVerifying Nilearn anatomical atlas connectivity...")
try:
    # Quick sanity check download of the Harvard-Oxford structural atlas
    ho_atlas = datasets.fetch_atlas_harvard_oxford('cort-maxprob-thr25-2mm')
    print(f"Atlas Verified: Successfully located cortical atlas containing {len(ho_atlas.labels)} structural regions.")
except Exception as e:
    print(f"Failed to verify Atlas fetching. Error: {e}")

print("\nVALIDATION SUCCESSFUL: You are cleared to proceed to Cell 2.")

# Commented out IPython magic to ensure Python compatibility.
# =============================================================================
# CELL 2: AUTOMATED MULTI-SUBJECT DATA FETCHER
# =============================================================================
print("Starting Cell 2: Initiating Multi-Subject Data Fetcher (Sub-01 to Sub-16)...")

dataset_dir = '/content/ds000001'

# 1. Clean up stale repository footprints if a reset is required
if not os.path.exists(os.path.join(dataset_dir, '.datalad')):
    if os.path.exists(dataset_dir):
        print(f"Removing non-DataLad directory at {dataset_dir}...")
        !rm -rf {dataset_dir}

    print("Cloning DataLad dataset ds000001 from OpenNeuro...")
#     %cd /content
    !datalad clone --reckless auto https://github.com/OpenNeuroDatasets/ds000001.git ds000001
else:
    print(f"Valid DataLad workspace already initialized at {dataset_dir}")

# Ensure we are inside the dataset working directory
# %cd {dataset_dir}
print(f"Working directory established: {os.getcwd()}")

# 2. Enable the public Amazon S3 remote mirror
print("Activating s3-PUBLIC fast-download mirror...")
!datalad siblings enable -s s3-PUBLIC > /dev/null 2>&1

# 3. Define the Robust Multi-Subject Fetcher
def fetch_subject_files(sub_id):
    """Downloads the mandatory BIDS NIfTI and TSV files for a target subject."""
    sub_str = f"sub-{sub_id:02d}"

    # Target files mapping based on the BIDS dataset design
    files_to_get = {
        "fMRI NIfTI": f"{sub_str}/func/{sub_str}_task-balloonanalogrisktask_run-01_bold.nii.gz",
        "Events TSV": f"{sub_str}/func/{sub_str}_task-balloonanalogrisktask_run-01_events.tsv"
    }

    download_status = {}

    for desc, rel_path in files_to_get.items():
        full_path = os.path.join(dataset_dir, rel_path)

        # Check if file exists and contains real data (not just a Git pointer link)
        if os.path.exists(full_path) and os.path.getsize(full_path) > 500:
            download_status[desc] = True
            continue

        print(f"Fetching {sub_str} {desc}...")

        # Strategy 1: DataLad native download
        try:
            !datalad get -d . "{rel_path}" > /dev/null 2>&1
            if os.path.exists(full_path) and os.path.getsize(full_path) > 500:
                print(f"    {sub_str} {desc} fetched via DataLad.")
                download_status[desc] = True
                continue
        except:
            pass

        # Strategy 2: Explicit DataLad S3 override
        try:
            !datalad get -d . -s s3-PUBLIC "{rel_path}" > /dev/null 2>&1
            if os.path.exists(full_path) and os.path.getsize(full_path) > 500:
                print(f"    {sub_str} {desc} fetched via s3-PUBLIC.")
                download_status[desc] = True
                continue
        except:
            pass

        # Strategy 3: HTTP Direct Download fallback
        if rel_path.endswith('.tsv'):
            import urllib.request
            try:
                direct_url = f"https://dl.openneuro.org/ds000001/{rel_path}"
                os.makedirs(os.path.dirname(full_path), exist_ok=True)
                urllib.request.urlretrieve(direct_url, full_path)
                if os.path.exists(full_path) and os.path.getsize(full_path) > 500:
                    print(f"    {sub_str} {desc} fetched via direct HTTP fallback.")
                    download_status[desc] = True
                    continue
            except:
                pass

        print(f"ERROR: Failed to acquire {desc} for {sub_str}")
        download_status[desc] = False

    return download_status

# 4. Global Dataset-Wide Metadata Sidecar Fetch
print("\nFetching global BIDS inheritance metadata file...")
global_json = 'task-balloonanalogrisktask_bold.json'
global_json_full = os.path.join(dataset_dir, global_json)
if not os.path.exists(global_json_full) or os.path.getsize(global_json_full) < 10:
    !datalad get -d . "{global_json}" > /dev/null 2>&1

# 5. Execute Loop over all 16 subjects
print("\nStarting batch sequence downloads for Subjects 1 through 16...")
from tqdm import tqdm

cohort_manifest = {}
for i in range(1, 17):
    print(f"\nProcessing Subject Cluster {i}/16:")
    status = fetch_subject_files(i)
    cohort_manifest[f"sub-{i:02d}"] = status

print("\nCELL 2 FINISHED: Download pipeline loop execution completed.")

# =============================================================================
# CELL 2-CHECK: BIDS DIRECTORY AUDIT
# =============================================================================
print("Running Cell 2 Validation Check: Storage Workspace Audit...\n")

dataset_dir = '/content/ds000001'
audit_records = []
missing_elements = 0

# Check global JSON file
json_path = os.path.join(dataset_dir, 'task-balloonanalogrisktask_bold.json')
json_ok = os.path.exists(json_path) and os.path.getsize(json_path) > 10
print(f"Global Metadata JSON Status: {'VALID' if json_ok else 'MISSING OR CORRUPTED'}\n")

# Audit individual subjects
for i in range(1, 17):
    sub_str = f"sub-{i:02d}"
    nii_path = os.path.join(dataset_dir, sub_str, 'func', f"{sub_str}_task-balloonanalogrisktask_run-01_bold.nii.gz")
    tsv_path = os.path.join(dataset_dir, sub_str, 'func', f"{sub_str}_task-balloonanalogrisktask_run-01_events.tsv")

    nii_exists = os.path.exists(nii_path) and os.path.getsize(nii_path) > 1000000  # Must be > 1MB
    tsv_exists = os.path.exists(tsv_path) and os.path.getsize(tsv_path) > 500      # Must be > 500 bytes

    nii_size_mb = os.path.getsize(nii_path) / (1024 * 1024) if os.path.exists(nii_path) else 0

    audit_records.append({
        "Subject": sub_str,
        "fMRI NIfTI": "Ready" if nii_exists else "Missing/Corrupt",
        "Size (MB)": f"{nii_size_mb:.1f} MB" if nii_exists else "0 MB",
        "Events TSV": "Ready" if tsv_exists else "Missing/Corrupt"
    })

    if not nii_exists or not tsv_exists:
        missing_elements += 1

# Display results in a highly readable dataframe format
audit_df = pd.DataFrame(audit_records)
print(audit_df.to_string(index=False))

print("\n" + "="*50)
if missing_elements == 0 and json_ok:
    print("VALIDATION SUCCESSFUL: All 16 subjects successfully verified on disk.")
    print("   You are cleared to proceed to Cell 3.")
else:
    print(f"WARNING: Data integrity gaps detected. Total problematic subjects: {missing_elements}")
    print("   Please check your network connection and re-run Cell 2 if critical scans are missing.")
print("="*50)

"""PART II: THE SPATIOTEMPORAL DATA EXTRACTION LOOP"""

# =============================================================================
# CELL 3: NEURAL NETWORK ARCHITECTURE & SKLEARN WRAPPER
# =============================================================================
print("Starting Cell 3: Compiling PyTorch Architecture & Sklearn Wrapper...")

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, TensorDataset
import numpy as np
from sklearn.base import BaseEstimator, ClassifierMixin

# 1. PyTorch Specialized fMRI Dataset Constructor
class FMRI_Dataset(Dataset):
    """Efficiently maps numpy feature vectors into native PyTorch Tensors."""
    def __init__(self, X, y):
        self.X = torch.FloatTensor(X)
        self.y = torch.LongTensor(y)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]


# 2. Linear Neural Network Architecture (GPU-Accelerated Linear SVC Equivalent)
class LinearClassifier(nn.Module):
    """
    Single-layer linear neural mapping function for multi-class voxel decoding.
    Optimized for extremely high-dimensional sparse feature spaces (voxels).
    """
    def __init__(self, n_features, n_classes):
        super().__init__()
        self.linear = nn.Linear(n_features, n_classes)

    def forward(self, x):
        return self.linear(x)


# 3. Scikit-Learn Unified API Wrapper with Memory-Safe Cache Clearing
class PyTorchSklearnWrapper(BaseEstimator, ClassifierMixin):
    """
    Bridges PyTorch models into the Scikit-Learn validation ecosystem.
    Allows PyTorch backends to execute seamlessly inside sklearn's permutation routines.
    """
    def __init__(self, n_features, n_classes, device, epochs=30, lr=0.01, batch_size=32):
        self.n_features = n_features
        self.n_classes = n_classes
        self.device = device
        self.epochs = epochs
        self.lr = lr
        self.batch_size = batch_size
        self.model = None

    def fit(self, X, y):
        # Explicitly purge stale cache prior to sub-fold initialization
        if self.device.type == 'cuda':
            torch.cuda.empty_cache()

        # Transform inputs into device-allocated PyTorch structures
        X_tensor = torch.FloatTensor(X).to(self.device)
        y_tensor = torch.LongTensor(y).to(self.device)

        train_dataset = TensorDataset(X_tensor, y_tensor)
        train_loader = DataLoader(train_dataset, batch_size=self.batch_size, shuffle=True)

        # Build local model instance isolated to this specific split
        self.model = LinearClassifier(self.n_features, self.n_classes).to(self.device)
        criterion = nn.CrossEntropyLoss()
        optimizer = torch.optim.SGD(self.model.parameters(), lr=self.lr)

        # Optimization Training Loop
        self.model.train()
        for epoch in range(self.epochs):
            for batch_X, batch_y in train_loader:
                optimizer.zero_grad()
                outputs = self.model(batch_X)
                loss = criterion(outputs, batch_y)
                loss.backward()
                optimizer.step()

        # Memory cleanup: drop pointers to raw training tensors
        del X_tensor, y_tensor, train_dataset, train_loader
        if self.device.type == 'cuda':
            torch.cuda.empty_cache()

        return self

    def predict(self, X):
        self.model.eval()
        # Stream evaluation elements on demand through the target hardware device
        X_tensor = torch.FloatTensor(X).to(self.device)
        with torch.no_grad():
            outputs = self.model(X_tensor)
            predictions = torch.argmax(outputs, dim=1).cpu().numpy()

        del X_tensor, outputs
        return predictions

    def score(self, X, y):
        # Calculate standard classification precision baseline
        predictions = self.predict(X)
        return np.mean(predictions == y)

print("\nCELL 3 FINISHED: PyTorch classes and Scikit-Learn wrapper compiled in memory.")

# =============================================================================
# CELL 4: THE MULTI-SUBJECT PROCESSING HUB
# =============================================================================
print("Starting Cell 4: Running Multi-Subject Processing Loop (Sub-01 to Sub-16)...")

import os
import gc
import pandas as pd
import numpy as np
import torch
from nilearn.image import load_img, smooth_img, index_img
from nilearn.masking import compute_epi_mask, apply_mask
from nilearn import datasets
from nilearn.maskers import NiftiLabelsMasker
from sklearn.preprocessing import StandardScaler

# 1. Initialize Global Parameters & Target Device
dataset_dir = '/content/ds000001'
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
hrf_shift_tr = 3  # Shift forward by 3 TRs (6 seconds) to align for hemodynamic peak delay

# 2. Load the Harvard-Oxford Structural Brain Atlas
print("Loading Harvard-Oxford Cortical Atlas for region mapping...")
atlas_data = datasets.fetch_atlas_harvard_oxford('cort-maxprob-thr25-2mm', data_dir='/content/atlas')
atlas_maps = atlas_data.maps
atlas_labels = atlas_data.labels  # Index 0 is background/Outside Brain

# 3. Create Master Data Structures to Save Aggregated Group Metrics
group_accuracies = {}
group_regional_weights = []

# 4. Iterate over all 16 subjects
for sub_idx in range(1, 17):
    sub_str = f"sub-{sub_idx:02d}"
    print(f"\nPreprocessing & Training: {sub_str}...")

    # Define absolute paths
    fmri_path = os.path.join(dataset_dir, sub_str, 'func', f"{sub_str}_task-balloonanalogrisktask_run-01_bold.nii.gz")
    events_path = os.path.join(dataset_dir, sub_str, 'func', f"{sub_str}_task-balloonanalogrisktask_run-01_events.tsv")
    json_path = os.path.join(dataset_dir, 'task-balloonanalogrisktask_bold.json')

    try:
        # Load Repetition Time metadata
        with open(json_path, 'r') as f:
            tr = json.load(f).get('RepetitionTime', 2.0)

        # A. Load, Smooth, and Compute Brain Mask
        fmri_img = load_img(fmri_path)
        smoothed_img = smooth_img(fmri_img, fwhm=6)
        brain_mask = compute_epi_mask(fmri_img)
        n_volumes = smoothed_img.shape[-1]

        # B. Parse Event Log & Apply Hemodynamic Response Function (HRF) Shift
        events_df = pd.read_csv(events_path, sep='\t')
        volume_labels_all = np.array(['rest'] * n_volumes, dtype=object)

        for _, row in events_df.iterrows():
            onset_sec = row['onset']
            duration_sec = row['duration']
            trial_type = row['trial_type']

            # Convert physical timeline seconds directly to volume frames
            start_vol = int(np.floor(onset_sec / tr))
            end_vol = int(np.ceil((onset_sec + duration_sec) / tr))

            # Inject a temporal shift forward to account for the metabolic delay
            shifted_start = min(n_volumes, start_vol + hrf_shift_tr)
            shifted_end = min(n_volumes, end_vol + hrf_shift_tr)

            for vol_idx in range(shifted_start, shifted_end):
                volume_labels_all[vol_idx] = trial_type

        # Filter down exclusively to actively engaged trial blocks
        active_indices = [idx for idx, lbl in enumerate(volume_labels_all) if lbl != 'rest']
        filtered_img = index_img(smoothed_img, active_indices)
        filtered_labels = np.array(volume_labels_all[active_indices])

        unique_labels = np.unique(filtered_labels)
        if len(unique_labels) < 2:
            print(f"Skipping {sub_str}: Insufficient distinct trial conditions found.")
            continue

        # C. Feature Space Vector Extraction (Voxels Matrix)
        X_raw = apply_mask(filtered_img, brain_mask)
        scaler = StandardScaler()
        X = scaler.fit_transform(X_raw)

        label_encoder = {label: idx for idx, label in enumerate(unique_labels)}
        y = np.array([label_encoder[lbl] for lbl in filtered_labels])

        n_features = X.shape[1]
        n_classes = len(unique_labels)

        # D. Train Predictive Neural Network Wrapper
        model_wrapper = PyTorchSklearnWrapper(n_features=n_features, n_classes=n_classes, device=device, epochs=40)

        # We use a fast internal Stratified 2-Fold split to extract cross-validation baseline
        from sklearn.model_selection import StratifiedKFold
        skf = StratifiedKFold(n_splits=2, shuffle=True, random_state=42)
        cv_scores = []
        for train_idx, test_idx in skf.split(X, y):
            model_wrapper.fit(X[train_idx], y[train_idx])
            cv_scores.append(model_wrapper.score(X[test_idx], y[test_idx]))

        sub_accuracy = np.mean(cv_scores)
        group_accuracies[sub_str] = sub_accuracy
        print(f"   Cross-Validated Prediction Accuracy: {sub_accuracy:.4f}")

        # E. Fit Final Model on Full Subject Session Data to Extract Feature Weights
        model_wrapper.fit(X, y)
        raw_weights = model_wrapper.model.linear.weight.cpu().detach().numpy()

        # Isolate contrast weight matrix for binary classification maps
        if n_classes == 2:
            weight_vector = raw_weights[1] - raw_weights[0]
        else:
            weight_vector = raw_weights[0]  # Reference the primary baseline class

        # F. Map Feature Weights Back to 3D Space and Compute Regional Averages
        from nilearn.masking import unmask
        weight_img_3d = unmask(weight_vector, brain_mask)

        # Extract mean absolute structural importance values across the anatomical atlas
        labels_masker = NiftiLabelsMasker(labels_img=atlas_maps, resampling_target="labels", background_label=0)
        regional_coefficients = labels_masker.fit_transform(weight_img_3d).flatten()

        # Append calculated coefficients to the long-form group array
        for label_idx, roi_name in enumerate(atlas_labels):
            if label_idx == 0: continue  # Skip Background
            if label_idx - 1 < len(regional_coefficients):
                group_regional_weights.append({
                    "Subject": sub_str,
                    "Region": roi_name,
                    "Weight": regional_coefficients[label_idx - 1]
                })

    except Exception as e:
        print(f"Critical Failure encountered on {sub_str}. Error details: {e}")

    finally:
        # G. Aggressive Memory Reclamation to Secure Colab Runtime Footprint
        try:
            del fmri_img, smoothed_img, brain_mask, filtered_img, X_raw, X, y
        except NameError:
            pass
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        gc.collect()

# Convert extracted weight configurations to a central master frame
df_group_weights = pd.DataFrame(group_regional_weights)
print("CELL 4 FINISHED: Completed the Multi-Subject Loop.")

# =============================================================================
# CELL 4-CHECK: DATAFRAME & WEIGHT ARRAY INSPECTION
# =============================================================================
print("Running Cell 4 Validation Check: Deep Data Integrity Audit...\n")

# 1. Audit Core Accuracy Output Records
if len(group_accuracies) > 0:
    print(f"Extracted Accuracy Profiles: Found entries for {len(group_accuracies)}/16 subjects.")
    print("Individual Performance Metadata Summary:")
    for sub, acc in list(group_accuracies.items())[:4]:
        print(f"   * {sub}: Decoding Performance Score = {acc*100:.2f}%")
    if len(group_accuracies) > 4:
        print("     [... Listing truncated for presentation ...]")
else:
    print("ERROR: The performance map tracking object is entirely empty.")

print("-" * 60)

# 2. Audit Structural Brain Regional Matrix Distribution
if not df_group_weights.empty:
    print(f"Anatomical Weight Frame Found: Matrix rows loaded = {len(df_group_weights)}")
    print(f"Unique Brain Geographies Mapped: {df_group_weights['Region'].nunique()} independent structural labels.")

    # Print the top rows to check structure layouts
    print("\nSample Weights Structural Matrix Snapshot (First 5 records):")
    print(df_group_weights.head(5).to_string(index=False))

    # Check for NaN leaks
    nan_count = df_group_weights['Weight'].isna().sum()
    if nan_count == 0:
        print("\nData Quality Check: Zero NaN float-point gaps detected across the matrix data array.")
    else:
        print(f"\nWARNING: Found {nan_count} structural null data fields within the weight data stack.")
else:
    print("ERROR: The global structural brain weight frame failed to generate.")

print("\n" + "="*60)
if len(group_accuracies) > 0 and not df_group_weights.empty and nan_count == 0:
    print("VALIDATION SUCCESSFUL: Subject data structures and regional maps are fully verified.")
    print("   You are completely clear to proceed to Cell 5.")
else:
    print("VALIDATION FAILED: Core computational artifacts are either missing or incomplete.")
print("="*60)

"""PART III: GROUP-LEVEL AGGREGATION & HYPOTHESIS TESTING"""

# =============================================================================
# CELL 5: GROUP-LEVEL STATISTICAL SUMMARY
# =============================================================================
print("Starting Cell 5: Aggregating Group-Level Statistics...")

import os
import pandas as pd
import numpy as np
from scipy.stats import ttest_1samp

# 1. Convert the collected accuracy dictionary into a unified Pandas Series
scores_series = pd.Series(group_accuracies)
n_subjects = len(scores_series)

# 2. Calculate Cohort Population Descriptive Metrics
mean_accuracy = scores_series.mean()
std_accuracy = scores_series.std()
sem_accuracy = scores_series.sem()  # Standard Error of the Mean

# 3. Execute Parametric Hypothesis Testing (One-Sample t-test against 50% chance)
chance_baseline = 0.50
t_statistic, p_value = ttest_1samp(scores_series, chance_baseline)

# 4. Generate Publication-Grade Statistics Dashboard Printout
print("\n" + "="*70)
print("FINAL COHORT DECODING SUMMARY REPORT (N=16 Subjects)")
print("="*70)
print(f"• Population Mean Accuracy : {mean_accuracy*100:.10f}%")
print(f"• Standard Deviation (SD)  : {std_accuracy*100:.10f}%")
print(f"• Standard Error (SEM)     : {sem_accuracy*100:.10f}%")
print(f"• Performance Range        : [{scores_series.min()*100:.10f}% - {scores_series.max()*100:.10f}%]")
print("-" * 70)
print(f"Statistical Test: One-Sample t-test vs. Chance Baseline ({chance_baseline*100}%)")
print(f"• Calculated t-Statistic   : {t_statistic:.10f}")
print(f"• Degrees of Freedom (df)  : {n_subjects - 1}")
print(f"• Computed Population p-val: {p_value:.10f}")

# Determine significance statement
if p_value < 0.001:
    significance_text = "Highly Significant! (p < 0.001)"
elif p_value < 0.05:
    significance_text = "Statistically Significant! (p < 0.05)"
else:
    significance_text = "Not statistically significant at standard alpha thresholds (α=0.05)"

print(f"• Result Conclusion        : {significance_text}")
print("="*70 + "\n")

# FIX: Explicitly ensure the target directory exists before exporting the CSV
export_dir = '/content/ds000001/figures'
os.makedirs(export_dir, exist_ok=True)

# Save out a clean descriptive table for manuscript drafting
summary_df = pd.DataFrame(scores_series, columns=['Accuracy'])
summary_df.index.name = 'Subject'
summary_df.to_csv(os.path.join(export_dir, 'group_accuracy_report.csv'))
print("Accuracy matrix saved locally to figures/group_accuracy_report.csv")

print("\nCELL 5 FINISHED: Group analytics fully compiled.")

# =============================================================================
# CELL 5-CHECK: STATISTICAL PARAMETERS AUDIT (REVISED)
# =============================================================================
print("Running Cell 5 Validation Check: Statistical Parameters Audit...\n")

# 1. Verify calculated array metrics are safe numbers
nan_check = np.isnan(mean_accuracy) or np.isnan(t_statistic) or np.isnan(p_value)
file_saved = os.path.exists('/content/ds000001/figures/group_accuracy_report.csv')

if not nan_check:
    print(f"Metric Extractor Verified: Population Mean calculated at {mean_accuracy:.4f}")
    print(f"Hypothesis Engine Verified: t-statistic value stands at {t_statistic:.4f}")
    print(f"p-value Precision Lock   : Calculated value is clean: {p_value:.6f}")
    print(f"CSV Export Status        : File successfully written to disk = {file_saved}")

    # Run a deep conceptual layout check
    if p_value < 0.05:
        print("\nPRE-WRITTEN MANUSCRIPT SENTENCE FOR YOUR METHODOLOGY:")
        print(f"   \"A population-level analysis across all 16 participants confirmed that predictive ")
        print(f"   neural states could be successfully decoded above chance baseline parameters ")
        print(f"   (Mean Accuracy = {mean_accuracy*100:.2f}% \u00b1 {sem_accuracy*100:.2f}% SEM; ")
        print(f"   t({n_subjects-1}) = {t_statistic:.3f}, p = {p_value:.5f}).\"")
    else:
        print("\nNOTICE: Your model performance trends near chance distributions on a group level.")
else:
    print("ERROR: One or more computed values resulted in a NaN calculation anomaly.")

print("\n" + "="*60)
if not nan_check and len(scores_series) == 16 and file_saved:
    print("VALIDATION SUCCESSFUL: Cohort metrics and file systems are fully verified.")
    print("   You are completely clear to proceed to Cell 6.")
else:
    print("VALIDATION FAILED: Missing variables or export artifacts missing.")
print("="*60)

"""PART IV: THE SPATIOTEMPORAL DISCOVERY ENGINE"""

# =============================================================================
# CELL 6: MULTI-DIMENSIONAL SPATIAL ANALYSIS (OVERALL, SUBJECT, & EVENT SLICES)
# =============================================================================
print("Starting Upgraded Cell 6: Executing High-Dimensional Spatial Analysis...")

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Verification of the upstream matrix structure
if 'df_group_weights' not in globals() or df_group_weights.empty:
    raise NameError("Multi-subject weight data missing. Please execute Cell 4 successfully.")

# Copy the core dataframe and extract absolute predictive magnitude
df_slice = df_group_weights.copy()
df_slice['Abs_Weight'] = df_slice['Weight'].abs()

# Establish the figures export directory
export_dir = '/content/ds000001/figures'
os.makedirs(export_dir, exist_ok=True)

# -----------------------------------------------------------------------------
# DIMENSION A: COHORT OVERALL LEVEL (The Definitive Population Rank)
# -----------------------------------------------------------------------------
print("Processing Dimension A: Population-wide Overall Summary...")
overall_rank = df_slice.groupby('Region')['Abs_Weight'].agg(['mean', 'sem']).reset_index()
overall_rank.columns = ['Region', 'Overall_Mean_Abs_Weight', 'SEM']
overall_rank = overall_rank.sort_values(by='Overall_Mean_Abs_Weight', ascending=False).reset_index(drop=True)

# Save the full comprehensive cohort text report
overall_rank.to_csv(os.path.join(export_dir, 'spatial_rank_overall.csv'), index=False)

# -----------------------------------------------------------------------------
# DIMENSION B: BY PARTICIPANT SLICE (Inter-Subject Variability Map)
# -----------------------------------------------------------------------------
print("Processing Dimension B: Generating Cross-Participant Slices...")
# Create a pivot table: Rows = Regions, Columns = Subjects, Values = Abs Weights
pivot_subjects = df_slice.pivot_table(
    index='Region',
    columns='Subject',
    values='Abs_Weight',
    aggfunc='mean'
)
# Order the pivot rows by the cohort's overall top-performing regions
pivot_subjects = pivot_subjects.loc[overall_rank['Region']]
pivot_subjects.to_csv(os.path.join(export_dir, 'spatial_rank_by_participant.csv'))

# -----------------------------------------------------------------------------
# DIMENSION C: VISUALIZATION DASHBOARD (Multi-Panel Panel Compilation)
# -----------------------------------------------------------------------------
print("Plotting Grand Multi-Dimensional Spatial Dashboard...")
fig, axes = plt.subplots(2, 1, figsize=(14, 16), gridspec_kw={'height_ratios': [1, 1.2]})

# Top Panel: The Global Cohort Top 15 Profile
top_n = 15
df_top_overall = overall_rank.head(top_n)
sns.barplot(
    x='Overall_Mean_Abs_Weight', y='Region', data=df_top_overall,
    palette='flare_r', edgecolor='black', linewidth=1, ax=axes[0]
)
# Add exact error caps for variance representation across the group
for idx, row in df_top_overall.iterrows():
    axes[0].errorbar(
        x=row['Overall_Mean_Abs_Weight'], y=idx, xerr=row['SEM'],
        color='black', capsize=3, fmt='none', elinewidth=1.2
    )
axes[0].set_title('Panel I: Global Cohort Importance Ranking (Top 15 Areas)', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Mean Absolute Weight Vector Size ( SEM)')
axes[0].set_ylabel('Anatomical Atlas Region')
axes[0].grid(axis='x', linestyle='--', alpha=0.4)

# Bottom Panel: Large Participant Inter-Subject Heatmap Matrix
# Visualizes how all 16 subjects activate across your top brain structures
sns.heatmap(
    pivot_subjects.head(20), cmap='rocket', cbar_kws={'label': 'Mean Predictive Importance Vector'},
    linewidths=0.5, linecolor='gray', ax=axes[1], xticklabels=True, yticklabels=True
)
axes[1].set_title('Panel II: High-Dimensional Inter-Subject Mapping Matrix (Top 20 Areas across All 16 Brains)', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Individual Participant ID')
axes[1].set_ylabel('Anatomical Atlas Region')

plt.tight_layout(pad=3.0)
dashboard_path = os.path.join(export_dir, 'multidim_spatial_dashboard.png')
plt.savefig(dashboard_path, dpi=150, bbox_inches='tight')
plt.close()

# -----------------------------------------------------------------------------
# STATISTICAL INSIGHT PRINT ENGINE
# -----------------------------------------------------------------------------
print("\n" + "="*85)
print("HIGH-DIMENSIONAL NEUROIMAGING METRIC REPORT")
print("="*85)
print(f" Global Structural Top Hub: {overall_rank.loc[0, 'Region']} (Weight: {overall_rank.loc[0, 'Overall_Mean_Abs_Weight']:.8f})")
print(f" Most Variable Region across People: {pivot_subjects.std(axis=1).idxmax()}")
print(f" Most Consistent Region across People: {pivot_subjects.std(axis=1).idxmin()}")
print("-" * 85)
print(" Multi-subject csv data matrices safely dumped to the /figures/ workspace.")
print(" Grand visualization dashboard saved to: figures/multidim_spatial_dashboard.png")
print("="*85 + "\n")

print("CELL 6 FINISHED: Advanced multi-dimensional spatial ranking completed.")

# =============================================================================
# CELL 6-CHECK: HIGH-DIMENSIONAL ASSET VALIDATION
# =============================================================================
print("Running Cell 6 Validation Check: Multi-Dimensional Pivot Audit...\n")

# 1. Verify existence of written file assets
path_overall = '/content/ds000001/figures/spatial_rank_overall.csv'
path_pivot = '/content/ds000001/figures/spatial_rank_by_participant.csv'
path_img = '/content/ds000001/figures/multidim_spatial_dashboard.png'

assets_ok = os.path.exists(path_overall) and os.path.exists(path_pivot) and os.path.exists(path_img)

if assets_ok:
    print(f"Data Persistence Verification: All spreadsheet maps written cleanly.")
    print(f"Dashboard Matrix Resolution Check: Image generated size = {os.path.getsize(path_img)/1024:.2f} KB")

    # Check the dimensional shape of your participant-by-region pivot table
    print(f"Pivot Table Alignment Check: Detected {pivot_subjects.shape[0]} Brain Regions mapped across {pivot_subjects.shape[1]} Subjects.")

    print("\nSUBJECT-BY-SUBJECT VARIATION SNAPSHOT (Top 3 Brain Regions across first 4 subjects):")
    print(pivot_subjects.iloc[:3, :4].round(6).to_string())
else:
    print("ERROR: One or more data slice structures failed to serialize to disk.")

print("\n" + "="*60)
if assets_ok and pivot_subjects.shape == (48, 16):
    print("VALIDATION SUCCESSFUL: Multi-dimensional spatial slicing structures are fully locked.")
    print("   You are clear to step into Cell 7 to begin event-locked timeline windowing.")
else:
    print("VALIDATION FAILED: Pivot layout dimensions are misaligned.")
print("="*60)

# =============================================================================
# CELL 7: EVENT-LOCKED TIME WINDOWING
# =============================================================================
print("Starting Revised Cell 7: Running High-Dimensional Event-Locked Time Slicing...")

import os
import gc
import json
import pandas as pd
import numpy as np
from nilearn.image import load_img, smooth_img
from nilearn.maskers import NiftiLabelsMasker
from nilearn import datasets

# 1. Verification of upstream atlas metadata from Cell 4
if 'atlas_maps' not in globals() or 'atlas_labels' not in globals():
    print("Atlas objects missing from memory. Re-fetching quickly...")
    atlas_data = datasets.fetch_atlas_harvard_oxford('cort-maxprob-thr25-2mm', data_dir='/content/atlas')
    atlas_maps = atlas_data.maps
    atlas_labels = atlas_data.labels

# 2. Configuration of Global Temporal Window Parameters
dataset_dir = '/content/ds000001'
tr = 2.0  # Repetition Time (seconds per volume)

window_start_sec = -4.0
window_end_sec = 10.0

vols_before = int(abs(window_start_sec) / tr)  # -4s / 2s = 2 volumes lookback
vols_after = int(window_end_sec / tr)          # 10s / 2s = 5 volumes lookforward
time_axis_seconds = np.arange(window_start_sec, window_end_sec + tr, tr)

# Focus on our top functional hubs discovered in Cell 6
target_rois = ['Insular Cortex', 'Frontal Pole', 'Cingulate Gyrus, anterior division']
group_time_trajectories = []

# 3. Process each subject to extract raw timeseries segments
for sub_idx in range(1, 17):
    sub_str = f"sub-{sub_idx:02d}"

    fmri_path = os.path.join(dataset_dir, sub_str, 'func', f"{sub_str}_task-balloonanalogrisktask_run-01_bold.nii.gz")
    events_path = os.path.join(dataset_dir, sub_str, 'func', f"{sub_str}_task-balloonanalogrisktask_run-01_events.tsv")

    if not os.path.exists(fmri_path) or not os.path.exists(events_path):
        print(f"Skipping {sub_str}: Files missing from storage.")
        continue

    print(f"Extracting Chronological Epochs: {sub_str}...")

    try:
        # Load and extract parcellated region signals
        fmri_img = load_img(fmri_path)
        smoothed_img = smooth_img(fmri_img, fwhm=6)

        # FIX: Pass the memory object `atlas_maps` directly instead of a hardcoded path string
        labels_masker = NiftiLabelsMasker(
            labels_img=atlas_maps,
            resampling_target="data",
            background_label=0,
            standardize=True  # Z-score signals to protect variance against individual amplitude drifts
        )
        region_signals = labels_masker.fit_transform(smoothed_img)

        # Parse timestamps from behavioral files
        events_df = pd.read_csv(events_path, sep='\t')

        # Target your two primary event conditions
        for target_condition in ['pumps_demean', 'explode_demean']:
            cond_events = events_df[events_df['trial_type'] == target_condition]

            for _, event_row in cond_events.iterrows():
                onset_time = event_row['onset']
                event_vol_idx = int(np.round(onset_time / tr))

                # Boundary safety check
                if (event_vol_idx - vols_before >= 0) and (event_vol_idx + vols_after < region_signals.shape[0]):

                    for roi_name in target_rois:
                        if roi_name in atlas_labels:
                            roi_col_idx = atlas_labels.index(roi_name) - 1  # Subtract background index offset

                            # Slice the exact 8-volume trajectory block
                            signal_slice = region_signals[
                                (event_vol_idx - vols_before) : (event_vol_idx + vols_after + 1),
                                roi_col_idx
                            ]

                            for relative_frame, bold_val in enumerate(signal_slice):
                                group_time_trajectories.append({
                                    "Subject": sub_str,
                                    "Condition": "Risk-Taking (Pumps)" if "pump" in target_condition else "Loss Event (Explosion)",
                                    "Region": roi_name,
                                    "Relative_TR": relative_frame - vols_before,
                                    "Time_Seconds": time_axis_seconds[relative_frame],
                                    "BOLD_Signal": bold_val
                                })

    except Exception as e:
        print(f"Error processing time slots for {sub_str}: {e}")

    finally:
        # Purge memory buffers
        try: del fmri_img, smoothed_img, region_signals
        except: pass
        gc.collect()

# Convert chronological results pool to a central data frame
df_group_time = pd.DataFrame(group_time_trajectories)
print("CELL 7 FINISHED: Spatiotemporal time window arrays generated successfully.")

# =============================================================================
# CELL 7-CHECK: REVISED HORIZON VALIDATION AUDIT
# =============================================================================
print("Running Cell 7 Validation Check: Spatiotemporal Horizon Audit...\n")

if 'df_group_time' in globals() and not df_group_time.empty:
    print(f"Data Frame Pipeline Connection: Found active long-form time matrix.")
    print(f"   • Total Spatiotemporal Rows Logged: {len(df_group_time)}")

    expected_subjects = df_group_time['Subject'].nunique()
    expected_conditions = df_group_time['Condition'].nunique()
    expected_regions = df_group_time['Region'].nunique()
    expected_timepoints = df_group_time['Time_Seconds'].nunique()

    print(f"\nHIGH-DIMENSIONAL TEMPORAL DECOMPOSITION PROFILE:")
    print(f"   • Unique Subjects Processed : {expected_subjects}/16")
    print(f"   • Tracked Task Conditions   : {expected_conditions} ({df_group_time['Condition'].unique().tolist()})")
    print(f"   • Extracted Target Brain Hubs: {expected_regions} ({df_group_time['Region'].unique().tolist()})")
    print(f"   • Volumes Per Time-Window   : {expected_timepoints} intervals mapping [{df_group_time['Time_Seconds'].min()}s to {df_group_time['Time_Seconds'].max()}s]")

    print("\nTEMPORAL TRAJECTORY DATA SNAPSHOT:")
    print(df_group_time.head(5).to_string(index=False))

    nulls = df_group_time['BOLD_Signal'].isna().sum()
    print(f"\nData Integrity Verification: Found {nulls} missing data points in the BOLD array.")
else:
    print("ERROR: Temporal data frame is empty. The loop did not extract data points.")

print("\n" + "="*60)
if 'df_group_time' in globals() and not df_group_time.empty and nulls == 0:
    print("VALIDATION SUCCESSFUL: Chronological data structures are verified and balanced.")
    print("   You are completely clear to proceed to Cell 8.")
else:
    print("VALIDATION FAILED: Time metrics are missing or loops failed.")
print("="*60)

# =============================================================================
# CELL 8: THE SPATIOTEMPORAL TRAJECTORY DASHBOARD
# =============================================================================
print("Starting Cell 8: Generating Spatiotemporal Chronological Curves...")

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Verification of upstream time-series matrix from Cell 7
if 'df_group_time' not in globals() or df_group_time.empty:
    raise NameError("Spatiotemporal data matrix missing. Please run Cell 7 successfully.")

# Ensure figures directory exists
export_dir = '/content/ds000001/figures'
os.makedirs(export_dir, exist_ok=True)

# 2. Configure multi-panel subplots based on our 3 target brain hubs
target_rois = ['Insular Cortex', 'Frontal Pole', 'Cingulate Gyrus, anterior division']
fig, axes = plt.subplots(1, 3, figsize=(18, 5.5), sharey=True)

# Palette matching the scientific tone of the project
condition_palette = {
    "Risk-Taking (Pumps)": "#1f77b4",       # Deep Blue
    "Loss Event (Explosion)": "#d62728"     # Crimson Red
}

print("Rendering time-series curves with 95% confidence bands...")

# 3. Iterate over each region to paint its specific timeline panel
for idx, roi_name in enumerate(target_rois):
    ax = axes[idx]

    # Isolate data rows belonging to this region
    df_roi = df_group_time[df_group_time['Region'] == roi_name]

    # Draw the line trajectories across time using Seaborn's bootstrapping engine
    sns.lineplot(
        data=df_roi,
        x='Time_Seconds',
        y='BOLD_Signal',
        hue='Condition',
        palette=condition_palette,
        linewidth=2.5,
        errorbar=('ci', 95),  # Calculates standard error confidence bounds across the 16 subjects
        ax=ax
    )

    # Structural Annotations to assist graphic readability
    ax.axvline(x=0.0, color='gray', linestyle='--', linewidth=1.5, alpha=0.7)  # Event Trigger line
    ax.axhline(y=0.0, color='black', linestyle='-', linewidth=0.5, alpha=0.5)   # Zero Baseline line

    # Panel Layout Fine-Tuning
    ax.set_title(f'{roi_name}\nTemporal Trajectory', fontsize=12, fontweight='bold', pad=10)
    ax.set_xlabel('Time relative to event onset (Seconds)', fontsize=10)
    if idx == 0:
        ax.set_ylabel('Standardized BOLD Signal Amplitude', fontsize=11)
    ax.grid(True, linestyle=':', alpha=0.6)

    # Clean up the legend layout so it doesn't duplicate across plots
    if idx == 0:
        ax.legend(title='Task Phase', loc='upper right', frameon=True, facecolor='white', framealpha=0.9)
    else:
        ax.get_legend().remove()

# Master Chart Labels
plt.suptitle('Event-Locked Hemodynamic Trajectories across Top Predictive Brain Regions (N=16 Group Cohort)',
             fontsize=14, fontweight='bold', y=1.02)

plt.tight_layout()

# Save the final graphic file asset to disk
plot_out_path = os.path.join(export_dir, 'hemodynamic_trajectories.png')
plt.savefig(plot_out_path, dpi=150, bbox_inches='tight')
plt.close()

print("\n" + "="*70)
print("VISUALIZATION ENGINE SUCCESSFUL")
print(f"• Saved asset destination: figures/hemodynamic_trajectories.png")
print("• Matrix data analyzed   : 16 subjects, 2 conditions, 3 core regions mapped.")
print("="*70 + "\n")

print("CELL 8 FINISHED: Spatiotemporal trajectory charts successfully written.")

# =============================================================================
# CELL 8-CHECK: GRAPHICS VERIFICATION AUDIT
# =============================================================================
print("Running Cell 8 Validation Check: Dashboard Asset Verification...\n")

target_graphic = '/content/ds000001/figures/hemodynamic_trajectories.png'
graphic_exists = os.path.exists(target_graphic)

if graphic_exists:
    file_size = os.path.getsize(target_graphic) / 1024
    print("Graphic System Resolution Verified: Target file located.")
    print(f"   • Asset Location: {target_graphic}")
    print(f"   • Image Footprint Size: {file_size:.2f} KB")
    print("\nINTERPRETATION GUIDE FOR YOUR PLOTS:")
    print("   1. Check 'Time = 0.0s'. This is the precise instant the event occurred.")
    print("   2. Look for the peak response between 4.0s and 8.0s. This shows the biological lag.")
    print("   3. Note where the blue line splits from the red line. That visual gap represents")
    print("      the exact functional contrast your PyTorch neural network used to decode decisions!")
else:
    print("ERROR: The chronological trajectory plot file was not generated successfully.")

print("\n" + "="*60)
if graphic_exists and file_size > 10:
    print("VALIDATION SUCCESSFUL: Spatiotemporal plots are securely built.")
    print("   You are fully cleared to move to our final step: Cell 9 (HTML Executive Builder).")
else:
    print("VALIDATION FAILED: Image data missing or damaged.")
print("="*60)

# =============================================================================
# CELL 9: 3D WHOLE-BRAIN ANATOMICAL MAPPING
# =============================================================================
print("Starting Cell 9: Generating MNI Anatomical Brain Maps...")

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from nilearn import plotting
from nilearn.image import new_img_like, load_img
from nilearn import datasets

# 1. Dynamic Reconstruction of the Weight Vector from Cell 4 Dataframes
if 'df_group_weights' not in globals() or df_group_weights.empty:
    raise NameError("Multi-subject weight database not found. Please ensure Cell 4 completed successfully.")

print("Reconstructing group spatial weight matrices from cohort records...")

# Extract unique regional labels and their corresponding mean weights across the cohort
regional_means = df_group_weights.groupby('Region')['Weight'].mean()

# Load the master atlas layout directly to map regional labels to exact 3D voxel coordinates
atlas_data = datasets.fetch_atlas_harvard_oxford('cort-maxprob-thr25-2mm', data_dir='/content/atlas')
atlas_img = load_img(atlas_data.maps)
atlas_matrix = atlas_img.get_fdata()
atlas_labels = atlas_data.labels

# Create an empty 3D grid matching the atlas dimensions
weight_matrix_3d = np.zeros_like(atlas_matrix, dtype=np.float32)

# Repopulate the 3D physical brain space with our calculated model feature weights
for label_idx, roi_name in enumerate(atlas_labels):
    if roi_name == 'Background':
        continue
    if roi_name in regional_means.index:
        weight_matrix_3d[atlas_matrix == label_idx] = regional_means[roi_name]

# Wrap the raw 3D array back into a standard citable NIfTI brain image file format
weight_img_3d = new_img_like(atlas_img, weight_matrix_3d)

# Establish figures target directory
export_dir = '/content/ds000001/figures'
os.makedirs(export_dir, exist_ok=True)

# 2. Figure A: Render a 3D Glass Brain Projection with Colorbar Contrast Labels
print("Rendering 3D Orthogonal Glass Brain Projections...")
glass_brain_path = os.path.join(export_dir, 'brain_glass_projection.png')

fig_glass = plt.figure(figsize=(11, 5))
plotting.plot_glass_brain(
    weight_img_3d,
    display_mode='lzry',  # Left, Z-axis, Right, Y-axis view grid layout
    colorbar=True,
    cmap='bwr',           # Pure white baseline transition
    plot_abs=False,
    figure=fig_glass,
    title='PyTorch Voxel Weights: Risk vs. Control Glass Projection'
)

# Position labels at the top-right and bottom-right corners near the colorbar poles
fig_glass.text(0.95, 0.90, 'High-Risk Predictors (Positive Weights)', color='black', fontsize=9, weight='semibold', ha='right')
fig_glass.text(0.95, 0.10, 'Control Predictors (Negative Weights)', color='black', fontsize=9, weight='semibold', ha='right')

fig_glass.savefig(glass_brain_path, dpi=150, bbox_inches='tight')
plt.close(fig_glass)

# 3. Figure B: Render Standard Multi-Slice Anatomical Cuts with Colorbar Contrast Labels
print("Rendering Multi-Slice Cross-Sectional Anatomical Maps...")
slice_map_path = os.path.join(export_dir, 'brain_slice_cross_sections.png')

fig_slice = plt.figure(figsize=(13, 5))
plotting.plot_stat_map(
    weight_img_3d,
    display_mode='z',     # Cut along the horizontal Axial plane
    cut_coords=5,         # Draw 5 sequentially stepped slices through the volume
    colorbar=True,
    cmap='bwr',
    figure=fig_slice,
    title='Anatomical Localization of Decoding Weights (Axial Cut Footprints)'
)

# Position labels at the top-right and bottom-right corners near the colorbar poles
fig_slice.text(0.95, 0.90, 'High-Risk Predictors (Positive Weights)', color='black', fontsize=9, weight='semibold', ha='right')
fig_slice.text(0.95, 0.10, 'Control Predictors (Negative Weights)', color='black', fontsize=9, weight='semibold', ha='right')

fig_slice.savefig(slice_map_path, dpi=150, bbox_inches='tight')
plt.close(fig_slice)

print("\n" + "="*75)
print("VISUAL BRAIN MAPS GENERATED SUCCESSFULLY")
print(f"Saved Glass Brain View : figures/brain_glass_projection.png")
print(f"Saved Slice Cut View   : figures/brain_slice_cross_sections.png")
print("="*75)
print("\nCELL 9 FINISHED: Anatomical structural maps written to disk.")

# =============================================================================
# CELL 9-CHECK: 3D MAPPING VERIFICATION AUDIT
# =============================================================================
print(" Running Cell 9 Validation Check: 3D Mapping Audit...\n")

import os

glass_brain_path = '/content/ds000001/figures/brain_glass_projection.png'
slice_map_path = '/content/ds000001/figures/brain_slice_cross_sections.png'

glass_exists = os.path.exists(glass_brain_path)
slices_exists = os.path.exists(slice_map_path)

if glass_exists and slices_exists:
    print(" Glass Brain Matrix Target Located.")
    print(" Slice Cross-Section Target Located.")
    print(f"   • Filesize Preview: Glass Brain = {os.path.getsize(glass_brain_path)/1024:.2f} KB")
    print(f"   • Filesize Preview: Slices Map  = {os.path.getsize(slice_map_path)/1024:.2f} KB")
else:
    raise FileNotFoundError(" ERROR: One or both 3D brain map assets failed to write to disk.")

print("\n" + "="*60)
print(" VALIDATION SUCCESSFUL: 3D spatial brain mapping verified.")
print("   Pipeline execution state cleared for final packaging.")
print("="*60 + "\n")
print(" CELL 9 AUDIT FINISHED: Structural map file footprints validated.")

# =============================================================================
# CELL 10: OPEN-SCIENCE RESEARCH PACKAGE EXPORT
# =============================================================================
print(" Starting Cell 10: Compiling Complete Open-Science Research Package...")

import os
import json
import zipfile
import shutil
from google.colab import files

# 1. Define absolute path frameworks
source_figures_dir = '/content/ds000001/figures'
archive_root_dir = '/content/fmri_research_package'
zip_output_path = '/content/ds000001_complete_research_manifest.zip'

# Reset and build fresh file architectures
if os.path.exists(archive_root_dir):
    shutil.rmtree(archive_root_dir)
os.makedirs(os.path.join(archive_root_dir, 'statistics'), exist_ok=True)
os.makedirs(os.path.join(archive_root_dir, 'plots'), exist_ok=True)

print(" Gathering and structured-sorting pipeline data frames...")

# 2. Export High-Precision Group Statistical Logs to JSON
if 't_statistic' in globals() and 'p_value' in globals():
    stats_manifest = {
        "analysis_date": "2026-05-30",
        "dataset": "OpenNeuro ds000001",
        "sample_size_n": int(n_subjects) if 'n_subjects' in globals() else 16,
        "degrees_of_freedom": int(n_subjects - 1) if 'n_subjects' in globals() else 15,
        "chance_baseline_pct": 50.0,
        "calculated_population_mean_accuracy_pct": float(mean_accuracy * 100),
        "standard_deviation_sd_pct": float(std_accuracy * 100),
        "standard_error_sem_pct": float(sem_accuracy * 100),
        "one_sample_t_statistic": float(t_statistic),
        "high_precision_p_value": f"{p_value:.12f}",
        "hypothesis_rejection_alpha_0_05": bool(p_value < 0.05),
        "citable_methodology_string": f"Mean Accuracy = {mean_accuracy*100:.4f}% +/- {sem_accuracy*100:.4f}% SEM; t({n_subjects-1 if 'n_subjects' in globals() else 15}) = {t_statistic:.4f}, p = {p_value:.10f}"
    }
    with open(os.path.join(archive_root_dir, 'statistics', 'population_t_test_metrics.json'), 'w') as f:
        json.dump(stats_manifest, f, indent=4)

# Copy across all compiled data spreadsheets
for file_name in ['group_accuracy_report.csv', 'spatial_rank_overall.csv', 'spatial_rank_by_participant.csv']:
    src_path = os.path.join(source_figures_dir, file_name)
    if os.path.exists(src_path):
        shutil.copy(src_path, os.path.join(archive_root_dir, 'statistics', file_name))

# 3. Gather All High-Resolution Figure Assets (Including 3D Structural Scans)
print(" Packaging publication charts and 3D MNI brain maps into archive structures...")
target_plots_list = [
    'spatial_localization_ranking.png',
    'multidim_spatial_dashboard.png',
    'hemodynamic_trajectories.png',
    'brain_glass_projection.png',
    'brain_slice_cross_sections.png'
]

for plot_name in target_plots_list:
    src_plot = os.path.join(source_figures_dir, plot_name)
    if os.path.exists(src_plot):
        shutil.copy(src_plot, os.path.join(archive_root_dir, 'plots', plot_name))

# 4. Generate an Open-Science Data Dictionary / README
readme_content = """=============================================================================
OPEN-SCIENCE RESEARCH MANIFEST: COMPLETE fMRI VOXEL DECODING DATA PACKAGE
=============================================================================
Dataset Source: OpenNeuro ds000001 (Balloon Analog Risk Task)

DIRECTORY STRUCTURE:
/statistics
  - population_t_test_metrics.json : High-precision parameters for paper write-up.
  - group_accuracy_report.csv       : Cross-validated accuracy targets across all 16 subjects.
  - spatial_rank_overall.csv       : Harvard-Oxford absolute weight significance rankings.
  - spatial_rank_by_participant.csv: High-dimensional pivot matrix separating subjects.

/plots
  - brain_glass_projection.png       : 3D glass brain rendering of model feature weights.
  - brain_slice_cross_sections.png   : 5-slice axial anatomical cross-sections of weights.
  - spatial_localization_ranking.png : Group ranking bar chart.
  - multidim_spatial_dashboard.png  : Combined ranking and inter-subject variance heatmap.
  - hemodynamic_trajectories.png     : Event-locked BOLD curves (-4s to +10s) with 95% CIs.
"""
with open(os.path.join(archive_root_dir, 'README_RESEARCH_MANIFEST.txt'), 'w') as f:
    f.write(readme_content)

# 5. Compress Everything Into a Single Monolithic ZIP File
print(" Compressing data package into zip structure...")
with zipfile.ZipFile(zip_output_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, dirs, files_list in os.walk(archive_root_dir):
        for file in files_list:
            full_file_path = os.path.join(root, file)
            relative_archive_path = os.path.relpath(full_file_path, archive_root_dir)
            zipf.write(full_file_path, relative_archive_path)

print(" ARCHIVE PACKAGE BUNDLED SUCCESSFULLY.")
print(" Triggering browser download manager pop-up...")

# 6. Fire browser download sequence
files.download(zip_output_path)
print("\n CELL 10 FINISHED: Full structural research package saved to local download workspace.")

# =============================================================================
# CELL 10-CHECK: FINAL PACKAGE ARCHITECTURE VERIFICATION
# =============================================================================
print(" Running Cell 10 Validation Check: Final Package Audit...\n")

target_zip = '/content/ds000001_complete_research_manifest.zip'
zip_exists = os.path.exists(target_zip)

if zip_exists:
    zip_size_mb = os.path.getsize(target_zip) / (1024 * 1024)
    print(" File Footprint Verification: Compressed ZIP archive located successfully.")
    print(f"   • Package File Path: {target_zip}")
    print(f"   • Archive Data Size: {zip_size_mb:.2f} MB")

    print("\n ARCHIVE INTERNAL MANIFEST AUDIT (Reading Table of Contents):")
    with zipfile.ZipFile(target_zip, 'r') as z:
        archived_files = z.namelist()
        for f_path in sorted(archived_files):
            print(f"    [ZIP CONTENTS] -> {f_path}")
else:
    print(" ERROR: The compressed package zip target could not be compiled on disk.")

print("\n" + "="*60)
if zip_exists and len(archived_files) >= 7:
    print(" PIPELINE COMPLETE: Your end-to-end fMRI study is completely processed!")
    print("   The ZIP has downloaded. You have everything you need for a stellar manuscript.")
else:
    print(" VALIDATION FAILED: Final bundle is missing artifacts or incomplete.")
print("="*60)