# -*- coding: utf-8 -*-
"""D2 R1 AI Neuroscience.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K-a7fFKmKWw_KQyCZ_5PJb-2duV7ZiUX

PART I: INFRASTRUCTURE & MULTI-SUBJECT INGESTION
"""

# Commented out IPython magic to ensure Python compatibility.
# =============================================================================
# CELL 1: ENVIRONMENT PROVISIONING & GLOBAL CONFIGS
# =============================================================================
print("Starting Cell 1: Initializing infrastructure and dependencies...")

# 1. Install heavy dependencies quietly
print("Installing pip packages (nilearn, nibabel, datalad, torch)...")
# %pip install -q nilearn nibabel pandas datalad tqdm matplotlib seaborn
# %pip install -q torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

# 2. Install system-level git-annex and network configurations
print("Installing git-annex standalone package...")
!wget -nc -q https://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-amd64.tar.gz -O /tmp/git-annex-standalone-amd64.tar.gz
!mkdir -p /usr/local/lib/git-annex
!tar -xzf /tmp/git-annex-standalone-amd64.tar.gz -C /usr/local/lib/git-annex --strip-components=1

# Inject into environment path
import os
os.environ['PATH'] = '/usr/local/lib/git-annex:' + os.environ['PATH']
!ln -sf /usr/local/lib/git-annex/git-annex /usr/local/bin/git-annex
!ln -sf /usr/local/lib/git-annex/git-annex-shell /usr/local/bin/git-annex-shell

print("Reinstalling netbase for robust network protocols...")
!apt-get update -qq && apt-get install -y --reinstall netbase > /dev/null 2>&1

# 3. Configure Git Globally (Required for DataLad tracking)
print("Configuring global Git settings...")
!git config --global user.email "neuro_decoder@colab.internal"
!git config --global user.name "NeuroDecoderColab"
!git config --global init.defaultBranch main
!git config --global annex.backend-prefer "SHA256"
!git config --global annex.retry "3"

# 4. Core Python Imports
print("Importing core analytics frameworks...")
import pandas as pd
import numpy as np
import json
import sys
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import torch

# Neuroimaging tools
from nilearn import datasets, plotting
from nilearn.image import load_img, smooth_img, index_img
from nilearn.masking import compute_epi_mask, apply_mask

# Scikit-learn wrapper utilities
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.model_selection import StratifiedKFold, permutation_test_score
from sklearn.preprocessing import StandardScaler

# Set plotting defaults
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette("husl")
# %matplotlib inline

print("\nCELL 1 FINISHED: Environment is provisioned.")

# =============================================================================
# CELL 1-CHECK: HARDWARE & DEPENDENCIES SANITY AUDIT
# =============================================================================
print("Running Cell 1 Validation Check...\n")

# Check PyTorch & CUDA Capabilities
print(f"PyTorch Installation Version: {torch.__version__}")
cuda_available = torch.cuda.is_available()
print(f"CUDA GPU Acceleration Available: {cuda_available}")

if cuda_available:
    device_name = torch.cuda.get_device_name(0)
    device = torch.device('cuda')
    print(f"Hardware Target Found: Using GPU [{device_name}]")

    # Run a quick 1-second sanity computation directly inside the GPU cores
    print("Running GPU tensor-matrix verification test...")
    x = torch.rand(1000, 1000, device=device)
    y = torch.matmul(x, x)
    del x, y
    torch.cuda.empty_cache()
    print("GPU Verification Test: Matrix multiplication completed instantly.")
else:
    device = torch.device('cpu')
    print("WARNING: No GPU detected. Processing will fall back to CPU.")
    print("    If you are using Google Colab, go to Runtime -> Change runtime type -> Select T4 GPU.")

# Check Nilearn Atlas access
print("\nVerifying Nilearn anatomical atlas connectivity...")
try:
    # Quick sanity check download of the Harvard-Oxford structural atlas
    ho_atlas = datasets.fetch_atlas_harvard_oxford('cort-maxprob-thr25-2mm')
    print(f"Atlas Verified: Successfully located cortical atlas containing {len(ho_atlas.labels)} structural regions.")
except Exception as e:
    print(f"Failed to verify Atlas fetching. Error: {e}")

print("\nVALIDATION SUCCESSFUL: You are cleared to proceed to Cell 2.")

# Commented out IPython magic to ensure Python compatibility.
# =============================================================================
# CELL 2: AUTOMATED MULTI-SUBJECT DATA FETCHER
# =============================================================================
print("Starting Cell 2: Initiating Multi-Subject Data Fetcher (Sub-01 to Sub-16)...")

dataset_dir = '/content/ds000001'

# 1. Clean up stale repository footprints if a reset is required
if not os.path.exists(os.path.join(dataset_dir, '.datalad')):
    if os.path.exists(dataset_dir):
        print(f"Removing non-DataLad directory at {dataset_dir}...")
        !rm -rf {dataset_dir}

    print("Cloning DataLad dataset ds000001 from OpenNeuro...")
#     %cd /content
    !datalad clone --reckless auto https://github.com/OpenNeuroDatasets/ds000001.git ds000001
else:
    print(f"Valid DataLad workspace already initialized at {dataset_dir}")

# Ensure we are inside the dataset working directory
# %cd {dataset_dir}
print(f"Working directory established: {os.getcwd()}")

# 2. Enable the public Amazon S3 remote mirror
print("Activating s3-PUBLIC fast-download mirror...")
!datalad siblings enable -s s3-PUBLIC > /dev/null 2>&1

# 3. Define the Robust Multi-Subject Fetcher
def fetch_subject_files(sub_id):
    """Downloads the mandatory BIDS NIfTI and TSV files for a target subject."""
    sub_str = f"sub-{sub_id:02d}"

    # Target files mapping based on the BIDS dataset design
    files_to_get = {
        "fMRI NIfTI": f"{sub_str}/func/{sub_str}_task-balloonanalogrisktask_run-01_bold.nii.gz",
        "Events TSV": f"{sub_str}/func/{sub_str}_task-balloonanalogrisktask_run-01_events.tsv"
    }

    download_status = {}

    for desc, rel_path in files_to_get.items():
        full_path = os.path.join(dataset_dir, rel_path)

        # Check if file exists and contains real data (not just a Git pointer link)
        if os.path.exists(full_path) and os.path.getsize(full_path) > 500:
            download_status[desc] = True
            continue

        print(f"Fetching {sub_str} {desc}...")

        # Strategy 1: DataLad native download
        try:
            !datalad get -d . "{rel_path}" > /dev/null 2>&1
            if os.path.exists(full_path) and os.path.getsize(full_path) > 500:
                print(f"    {sub_str} {desc} fetched via DataLad.")
                download_status[desc] = True
                continue
        except:
            pass

        # Strategy 2: Explicit DataLad S3 override
        try:
            !datalad get -d . -s s3-PUBLIC "{rel_path}" > /dev/null 2>&1
            if os.path.exists(full_path) and os.path.getsize(full_path) > 500:
                print(f"    {sub_str} {desc} fetched via s3-PUBLIC.")
                download_status[desc] = True
                continue
        except:
            pass

        # Strategy 3: HTTP Direct Download fallback
        if rel_path.endswith('.tsv'):
            import urllib.request
            try:
                direct_url = f"https://dl.openneuro.org/ds000001/{rel_path}"
                os.makedirs(os.path.dirname(full_path), exist_ok=True)
                urllib.request.urlretrieve(direct_url, full_path)
                if os.path.exists(full_path) and os.path.getsize(full_path) > 500:
                    print(f"    {sub_str} {desc} fetched via direct HTTP fallback.")
                    download_status[desc] = True
                    continue
            except:
                pass

        print(f"ERROR: Failed to acquire {desc} for {sub_str}")
        download_status[desc] = False

    return download_status

# 4. Global Dataset-Wide Metadata Sidecar Fetch
print("\nFetching global BIDS inheritance metadata file...")
global_json = 'task-balloonanalogrisktask_bold.json'
global_json_full = os.path.join(dataset_dir, global_json)
if not os.path.exists(global_json_full) or os.path.getsize(global_json_full) < 10:
    !datalad get -d . "{global_json}" > /dev/null 2>&1

# 5. Execute Loop over all 16 subjects
print("\nStarting batch sequence downloads for Subjects 1 through 16...")
from tqdm import tqdm

cohort_manifest = {}
for i in range(1, 17):
    print(f"\nProcessing Subject Cluster {i}/16:")
    status = fetch_subject_files(i)
    cohort_manifest[f"sub-{i:02d}"] = status

print("\nCELL 2 FINISHED: Download pipeline loop execution completed.")

# =============================================================================
# CELL 2-CHECK: BIDS DIRECTORY AUDIT
# =============================================================================
print("Running Cell 2 Validation Check: Storage Workspace Audit...\n")

dataset_dir = '/content/ds000001'
audit_records = []
missing_elements = 0

# Check global JSON file
json_path = os.path.join(dataset_dir, 'task-balloonanalogrisktask_bold.json')
json_ok = os.path.exists(json_path) and os.path.getsize(json_path) > 10
print(f"Global Metadata JSON Status: {'VALID' if json_ok else 'MISSING OR CORRUPTED'}\n")

# Audit individual subjects
for i in range(1, 17):
    sub_str = f"sub-{i:02d}"
    nii_path = os.path.join(dataset_dir, sub_str, 'func', f"{sub_str}_task-balloonanalogrisktask_run-01_bold.nii.gz")
    tsv_path = os.path.join(dataset_dir, sub_str, 'func', f"{sub_str}_task-balloonanalogrisktask_run-01_events.tsv")

    nii_exists = os.path.exists(nii_path) and os.path.getsize(nii_path) > 1000000  # Must be > 1MB
    tsv_exists = os.path.exists(tsv_path) and os.path.getsize(tsv_path) > 500      # Must be > 500 bytes

    nii_size_mb = os.path.getsize(nii_path) / (1024 * 1024) if os.path.exists(nii_path) else 0

    audit_records.append({
        "Subject": sub_str,
        "fMRI NIfTI": "Ready" if nii_exists else "Missing/Corrupt",
        "Size (MB)": f"{nii_size_mb:.1f} MB" if nii_exists else "0 MB",
        "Events TSV": "Ready" if tsv_exists else "Missing/Corrupt"
    })

    if not nii_exists or not tsv_exists:
        missing_elements += 1

# Display results in a highly readable dataframe format
audit_df = pd.DataFrame(audit_records)
print(audit_df.to_string(index=False))

print("\n" + "="*50)
if missing_elements == 0 and json_ok:
    print("VALIDATION SUCCESSFUL: All 16 subjects successfully verified on disk.")
    print("   You are cleared to proceed to Cell 3.")
else:
    print(f"WARNING: Data integrity gaps detected. Total problematic subjects: {missing_elements}")
    print("   Please check your network connection and re-run Cell 2 if critical scans are missing.")
print("="*50)

"""PART II: THE SPATIOTEMPORAL DATA EXTRACTION LOOP"""

# =============================================================================
# CELL 3: NEURAL NETWORK ARCHITECTURE & SKLEARN WRAPPER
# =============================================================================
print("Starting Cell 3: Compiling PyTorch Architecture & Sklearn Wrapper...")

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, TensorDataset
import numpy as np
from sklearn.base import BaseEstimator, ClassifierMixin

# 1. PyTorch Specialized fMRI Dataset Constructor
class FMRI_Dataset(Dataset):
    """Efficiently maps numpy feature vectors into native PyTorch Tensors."""
    def __init__(self, X, y):
        self.X = torch.FloatTensor(X)
        self.y = torch.LongTensor(y)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]


# 2. Linear Neural Network Architecture (GPU-Accelerated Linear SVC Equivalent)
class LinearClassifier(nn.Module):
    """
    Single-layer linear neural mapping function for multi-class voxel decoding.
    Optimized for extremely high-dimensional sparse feature spaces (voxels).
    """
    def __init__(self, n_features, n_classes):
        super().__init__()
        self.linear = nn.Linear(n_features, n_classes)

    def forward(self, x):
        return self.linear(x)


# 3. Scikit-Learn Unified API Wrapper with Memory-Safe Cache Clearing
class PyTorchSklearnWrapper(BaseEstimator, ClassifierMixin):
    """
    Bridges PyTorch models into the Scikit-Learn validation ecosystem.
    Allows PyTorch backends to execute seamlessly inside sklearn's permutation routines.
    """
    def __init__(self, n_features, n_classes, device, epochs=30, lr=0.01, batch_size=32):
        self.n_features = n_features
        self.n_classes = n_classes
        self.device = device
        self.epochs = epochs
        self.lr = lr
        self.batch_size = batch_size
        self.model = None

    def fit(self, X, y):
        # Explicitly purge stale cache prior to sub-fold initialization
        if self.device.type == 'cuda':
            torch.cuda.empty_cache()

        # Transform inputs into device-allocated PyTorch structures
        X_tensor = torch.FloatTensor(X).to(self.device)
        y_tensor = torch.LongTensor(y).to(self.device)

        train_dataset = TensorDataset(X_tensor, y_tensor)
        train_loader = DataLoader(train_dataset, batch_size=self.batch_size, shuffle=True)

        # Build local model instance isolated to this specific split
        self.model = LinearClassifier(self.n_features, self.n_classes).to(self.device)
        criterion = nn.CrossEntropyLoss()
        optimizer = torch.optim.SGD(self.model.parameters(), lr=self.lr)

        # Optimization Training Loop
        self.model.train()
        for epoch in range(self.epochs):
            for batch_X, batch_y in train_loader:
                optimizer.zero_grad()
                outputs = self.model(batch_X)
                loss = criterion(outputs, batch_y)
                loss.backward()
                optimizer.step()

        # Memory cleanup: drop pointers to raw training tensors
        del X_tensor, y_tensor, train_dataset, train_loader
        if self.device.type == 'cuda':
            torch.cuda.empty_cache()

        return self

    def predict(self, X):
        self.model.eval()
        # Stream evaluation elements on demand through the target hardware device
        X_tensor = torch.FloatTensor(X).to(self.device)
        with torch.no_grad():
            outputs = self.model(X_tensor)
            predictions = torch.argmax(outputs, dim=1).cpu().numpy()

        del X_tensor, outputs
        return predictions

    def score(self, X, y):
        # Calculate standard classification precision baseline
        predictions = self.predict(X)
        return np.mean(predictions == y)

print("\nCELL 3 FINISHED: PyTorch classes and Scikit-Learn wrapper compiled in memory.")

# =============================================================================
# CELL 4: THE MULTI-SUBJECT PROCESSING HUB
# =============================================================================
print("Starting Cell 4: Running Multi-Subject Processing Loop (Sub-01 to Sub-16)...")

import os
import gc
import pandas as pd
import numpy as np
import torch
from nilearn.image import load_img, smooth_img, index_img
from nilearn.masking import compute_epi_mask, apply_mask
from nilearn import datasets
from nilearn.maskers import NiftiLabelsMasker
from sklearn.preprocessing import StandardScaler

# 1. Initialize Global Parameters & Target Device
dataset_dir = '/content/ds000001'
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
hrf_shift_tr = 3  # Shift forward by 3 TRs (6 seconds) to align for hemodynamic peak delay

# 2. Load the Harvard-Oxford Structural Brain Atlas
print("Loading Harvard-Oxford Cortical Atlas for region mapping...")
atlas_data = datasets.fetch_atlas_harvard_oxford('cort-maxprob-thr25-2mm', data_dir='/content/atlas')
